Repository siristechnology/nepaltoday-app, pull requests merged in 2019-09, with the labels that each got.

#28 Create CODEOWNERS.md
  docs/CODEOWNERS.md
Labels: size/XS

#29 error-boundary: global error boundry with toast is completed
  app.js
  schema.graphql
  src/error/error-boundry.js
  src/error/error-boundry.test.js
  src/frame/app-container.js
  src/screens/__generated__/headlineScreenQuery.graphql.js
  src/screens/headline.screen.js
  src/screens/tests/headline-screen.test.js
  yarn.lock
Labels: size/M

#30 Error boundary
  src/screens/__generated__/headlineScreenQuery.graphql.js
  src/screens/headline.screen.js
  src/twitter/TwitterCard.js
  src/twitter/__generated__/twitterQuery.graphql.js
  src/twitter/index.js
Labels: size/M

#32 Nep 58 font size
  .eslintrc.json
  .prettierrc
  .vscode/settings.json
  src/home/components/article-card.js
  src/home/components/article-detail.screen.js
  src/screens/__generated__/headlineScreenQuery.graphql.js
Labels: size/M

#34 Nep 59 twitter spinner
  src/twitter/__generated__/twitterQuery.graphql.js
  src/twitter/index.js
Labels: size/M

#38 Nep 63 fix refresh issue
  src/frame/app-container.js
  src/frame/app-layout.js
  src/home/components/bottom-navigation.js
  src/home/components/bottom-navigation/index.js
  src/home/index.js
  src/screens/headline.screen.js
  src/tests/components/bottom-navigation.test.js
  src/twitter/index.js
Labels: size/L

#36 Nep 62 add more btn
  android/app/build.gradle
  android/app/src/main/java/com/nepaltodayapp/MainApplication.java
  android/gradle.properties
  android/settings.gradle
  ios/Podfile
  ios/nepaltodayapp.xcodeproj/project.pbxproj
  package.json
  src/article/index.js
  src/home/components/article-detail.screen.js
  src/home/components/bottom-navigation.js
  src/lang/np.js
  yarn.lock
Labels: size/M

#43 Nep 60 fixed headline navigation
  src/screens/headline.screen.js
Labels: size/S

#44 Hotfix/twitter date
  schema.graphql
  src/twitter/TwitterCard.js
  src/twitter/__generated__/twitterQuery.graphql.js
  src/twitter/index.js
Labels: size/S

#54 Feature/article dim
  package.json
  src/components/article-card.component.js
  src/screens/home-screen/home.screen.js
  yarn.lock
Labels: size/L

#55 Feature/adding image element
  package.json
  src/components/article-card.component.js
  src/components/article-detail.component.js
  src/style.js
  yarn.lock
Labels: size/L

#57 Nep 86 open twitter
  app.test.js
  jest.config.js
  package.json
  schema.graphql
  src/components/article-card.component.js
  src/components/offline-notification.component.js
  src/components/twitter-card.component.js
  src/environment.js
  src/screens/headline-screen/headline-screen.test.js
  src/screens/home-screen/home.screen.js
  src/screens/twitter-screen/__generated__/twitterQuery.graphql.js
  src/screens/twitter-screen/twitter.screen.js
  yarn.lock
Labels: size/XXL

#58 nep-84-redesign-article-detail: article page redesing
  src/components/article-detail.component.js
Labels: size/M

#60 nep-89-webview-loading: webview loading is shown
  src/components/article-webview.component.js
Labels: size/S

#61 nep-78-refresh-btn: refresh btn in splash screen when internet is off
  app.js
  src/components/offline-notification.component.js
  src/components/splash-screen.component.js
  src/frame/app-container.js
  src/lang/np.js
  src/screens/navigation/bottom-navigation.screen.js
Labels: size/L

#62 nep-91-increase-webview-loader: spiner added for webview
  src/components/article-webview.component.js
Labels: size/XS

#63 Nep 94 time component
  src/components/article-card.component.js
  src/components/article-detail.component.js
  src/components/index.js
  src/components/time.component.js
  src/components/twitter-card.component.js
Labels: size/L

#64 nep-96-bug-app-crash: resolved issues for app crash when content is null
  src/components/article-detail.component.js
Labels: size/XS

#65 nep-97-bug-app-freeze-internet: internet unavailable screen added to …
  app.js
  src/screens/headline-screen/headline.screen.js
  src/screens/home-screen/home.screen.js
  src/screens/twitter-screen/twitter.screen.js
Labels: size/L

#68 Nep 108 icon change
  app.js
  src/components/article-card.component.js
  src/screens/headline-screen/headline.screen.js
  src/screens/home-screen/home.screen.js
  src/screens/twitter-screen/twitter.screen.js
Labels: size/L
