Repository siristechnology/nepaltoday-app, pull requests merged in 2020-12, with the labels that each got.

#214 NEP-304 : dark mode
  app.js
  index.js
  src/components/article-webview.component.js
  src/components/offline-notification.component.js
  src/frame/app-container.js
  src/frame/app-layout.js
  src/layout/article/article-list/article-list-item.component.js
  src/layout/article/article-list/article-list.component.js
  src/layout/headline/tab-view/headline-list.component.js
  src/layout/twitter/twitter-list-item.component.js
  src/layout/twitter/twitter-list.component.js
  src/screens/corona-screen/corona.screen.js
  src/screens/corona-screen/coronaCountryStats/countryCard.js
  src/screens/corona-screen/coronaCountryStats/countryList.js
  src/screens/corona-screen/coronaDistrictStats/coronaSummary.js
  src/screens/corona-screen/coronaDistrictStats/districtCard.js
  src/screens/corona-screen/coronaDistrictStats/districtList.js
  src/screens/headline-screen/headline.screen.js
  src/screens/home-screen/components/article-list/article-list-container.component.js
  src/screens/home-screen/components/article-list/article-list.component.js
  src/screens/home-screen/components/article-list/article.component.js
  src/screens/home-screen/components/article-list/showMoreModal.js
  src/screens/home-screen/components/nepaliEvent.component.js
  src/screens/home-screen/components/storyHeadline/roundStory.js
  src/screens/home-screen/components/weather.component.js
  src/screens/home-screen/home.screen.js
  src/screens/navigation/bottom-navigation.screen.js
  src/screens/radio-screen/allRadio.js
  src/screens/radio-screen/components/allRadioListContainer.js
  src/screens/radio-screen/components/bottomPlayer.js
  src/screens/radio-screen/components/radioCard.js
  src/screens/radio-screen/favoriteRadio.js
  src/screens/radio-screen/radio.screen.js
  src/screens/settings-screen/settings.screen.js
  src/screens/trending-screen/trending-detail/index.js
  src/screens/trending-screen/trending-detail/trendingNewsDetail.js
  src/screens/trending-screen/trending-detail/trendingTweetDetail.js
  src/screens/trending-screen/trending-tabs/index.js
  src/screens/trending-screen/trending-tabs/trending-persons/components/trendingCard.js
  src/screens/trending-screen/trending-tabs/trending-persons/components/trendingDetail/index.js
  src/screens/trending-screen/trending-tabs/trending-persons/components/trendingListContainer.js
Labels: size/XL

#215 NEP-304 : story wrong issue and dark mode preserve issue fixed
  index.js
  src/screens/home-screen/components/storyHeadline/storyHeadline.js
  src/screens/home-screen/components/storyHeadline/swiperStory.js
  src/services/asyncStorageService.js
Labels: size/M

#217 Fm api integrated
  src/screens/radio-screen/components/radioCard.js
  src/screens/radio-screen/radio.screen.js
Labels: size/M

#218 NEP-303 Jest tests for Headline screen
  .prettierrc
  app.js
  app.test.js
  index.js
  jest/setup.js
  package.json
  src/error/error-boundry.js
  src/frame/app-container.js
  src/helper/cacheStorage.js
  src/screens/corona-screen/corona.screen.test.js
  src/screens/headline-screen/headline-screen.test.js
  src/screens/headline-screen/headline.screen.js
  src/screens/home-screen/components/storyHeadline/storyStorageservices.js
  src/services/asyncStorageService.js
  yarn.lock
Labels: size/L

#219 NEP-303 : Test case for all main screens
  src/screens/corona-screen/corona.screen.test.js
  src/screens/corona-screen/coronaDistrictStats/districtList.js
  src/screens/home-screen/home.screen.test.js
  src/screens/radio-screen/radio.screen.test.js
  src/screens/trending-screen/trending-screen.test.js
  src/screens/trending-screen/trending-tabs/trending-persons/trending.screen.js
  src/screens/trending-screen/trending-tabs/trending-tweets/twitter.screen.js
Labels: size/L

#220 NEP-308 : Unreadable detail story issue
  src/screens/home-screen/components/storyHeadline/swiperStory.js
Labels: size/XS

#221 NEP-329 : back button for notification
  src/layout/article/article-detail/article-detail.component.tsx
Labels: size/S

#222 NEP-336 : Swipe feature
  src/screens/home-screen/components/storyHeadline/storyHeadline.js
  src/screens/home-screen/components/storyHeadline/storyStorageservices.js
  src/screens/home-screen/components/storyHeadline/swiperStory.js
Labels: size/S

#223 NEP-319 : app sharing added
  src/screens/settings-screen/settings.screen.js
Labels: size/S

#224 Weather not visible issue fixed
  src/screens/home-screen/home.screen.js
Labels: size/XS

#225 NEP-305 : Top 5 trending tags added
  src/frame/app-container.js
  src/layout/article/article-detail/article-detail.component.tsx
  src/layout/article/article-list/article-list-container.component.js
  src/screens/home-screen/components/nepaliEvent.component.js
  src/screens/home-screen/components/trendingTag.component.js
  src/screens/home-screen/home.screen.js
  src/screens/tagArticle-screen/tagArticle.screen.js
Labels: size/L

#226 NEP-330 : Request animation frame firebase error
  package.json
  yarn.lock
Labels: size/M
