Repository siristechnology/nepaltoday-app, pull requests merged in 2020-02, with the labels that each got.

#91 W9 add date weather to header
  android/app/src/main/AndroidManifest.xml
  global.js
  package.json
  src/components/weather.component.js
  src/frame/app-layout.js
  src/helper/dateConverter.js
  src/helper/dateFormatter.js
  src/helper/time.js
  src/helper/utils.js
  src/screens/home-screen/home.screen.js
  yarn.lock
Labels: size/XL

#92 W9 add date weather to header some issues
  src/components/weather.component.js
  src/helper/utils.js
  src/screens/home-screen/home.screen.js
Labels: size/XL

#93 w9-scroll view issue
  src/frame/app-layout.js
Labels: size/XS

#94 w9-removed unused functions
  src/helper/dateConverter.js
Labels: size/L

#95 Copying some changes from master to release
  .github/workflows/android-publish.yml
Labels: size/XS
